## 1️⃣ 넘파이(NumPy)란?

> NumPy(Numerical Python) 는
> 
> 
> **수치 계산**을 빠르고 효율적으로 수행하기 위한 파이썬 핵심 라이브러리입니다.
> 

---

### 💡 한 줄 정의

> “리스트보다 빠르고, 수학적으로 강력한 배열 연산 도구”
> 

---

### 📊 NumPy가 필요한 이유

| 구분 | 파이썬 리스트 | 넘파이 배열 |
| --- | --- | --- |
| 구조 | 다양한 타입 저장 가능 | 동일한 타입의 데이터 저장 |
| 속도 | 느림 (for문 필요) | 빠름 (C 기반 벡터 연산) |
| 연산 | 직접 반복문 작성 필요 | 벡터화(Vectorization)로 한 줄 계산 |
| 용도 | 일반 데이터 저장 | 수치 연산, 통계, 머신러닝 입력용 |

---

### 💬 실무 예시

| 사례 | 넘파이 사용 이유 |
| --- | --- |
| 데이터 분석 | 대규모 CSV 수치 데이터 빠른 처리 |
| 이미지 분석 | 픽셀 데이터(행렬) 계산 |
| 머신러닝 | 학습용 행렬 데이터 저장 및 변환 |
| 통계 처리 | 평균, 표준편차, 분산 계산 등 자동화 |

In [1]:
import numpy as np

list_data = [1,2,3,4,5]
print(list_data)
type(list_data)


[1, 2, 3, 4, 5]


list

In [2]:
array_data = np.array(list_data)
print(array_data)
type(array_data)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# 배열 연산 비교

list_a = [1,2,3]
list_b = [4,5,6]
print(list_a + list_b) # 데이터의 결합

[1, 2, 3, 4, 5, 6]


In [ ]:
arr_a = np.array(list_a)
arr_b = np.array(list_b)

print(arr_a+arr_b)    # 행렬 합이 나옴

[5 7 9]


## 2️⃣ 배열(Array)의 개념

> 배열(array) 은 “동일한 자료형을 갖는 데이터의 집합”입니다.
> 
> 
> 엑셀의 셀(sheet), 행렬(matrix), 표(table)처럼 **행(row)과 열(column)** 로 구성됩니다.

## 3️⃣ 배열 생성 방법

### (1) 리스트로부터 생성

```python
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2차원 배열

```

---

### (2) 자동 생성 함수

| 함수 | 설명 | 예시 |
| --- | --- | --- |
| `np.zeros(n)` | 0으로 채운 배열 | `np.zeros(5)` |
| `np.ones(n)` | 1로 채운 배열 | `np.ones(5)` |
| `np.arange(start, stop, step)` | 일정 간격 숫자 생성 | `np.arange(1, 10, 2)` |
| `np.linspace(start, stop, n)` | 구간을 n등분 | `np.linspace(0, 1, 5)` |
| `np.random.rand(n)` | 0~1 사이 난수 생성 | `np.random.rand(5)` |

In [5]:
# 1차원 
arr_1 = np.array([1,2,3])

# 2차원
arr_2 = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

print(arr_1, arr_2)

[1 2 3] [[1 2 3]
 [2 3 4]
 [3 4 5]]


In [11]:
# 0으로 채운배열
print(np.zeros(3))

# 1로 채운 배열
print(np.ones(5))

# start, stop, step 배열생성
print(np.arange(1,10,2))

# 난수 생성
print(np.random.rand(3))

print(np.linspace(0, 1, 5))

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]
[0.78249777 0.17168984 0.79773493]
[0.   0.25 0.5  0.75 1.  ]


## 4️⃣ 배열의 속성 확인

> 배열 객체는 여러 속성을 가지고 있습니다.
> 

---

| 속성 | 설명 | 예시 출력 |
| --- | --- | --- |
| `.ndim` | 배열의 차원 수 | `1`, `2` |
| `.shape` | 배열의 크기 (행, 열) | `(2, 3)` |
| `.size` | 전체 원소 개수 | `6` |
| `.dtype` | 데이터 타입 | `int32`, `float64` |

---

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("차원:", arr.ndim)
print("크기:", arr.shape)
print("원소 개수:", arr.size)
print("데이터 타입:", arr.dtype)


차원: 2
크기: (2, 3)
원소 개수: 6
데이터 타입: int64


## 5️⃣ 배열의 기본 연산

> 넘파이는 for문 없이 전체 데이터를 한 번에 계산할 수 있습니다.
>

In [12]:
arr = np.array([10, 20, 30, 40])

print("➕ 덧셈:", arr + 5)
print("➖ 뺄셈:", arr - 10)
print("✖️ 곱셈:", arr * 2)
print("➗ 나눗셈:", arr / 10)
print("평균:", np.mean(arr))
print("표준편차:", np.std(arr))


➕ 덧셈: [15 25 35 45]
➖ 뺄셈: [ 0 10 20 30]
✖️ 곱셈: [20 40 60 80]
➗ 나눗셈: [1. 2. 3. 4.]
평균: 25.0
표준편차: 11.180339887498949


## 6️⃣ 🧩 실습 아이디어 — “단어 길이 통계 분석기”

> 텍스트 데이터를 수치형 배열로 변환해 간단한 통계 분석을 수행합니다.
>

In [14]:
import numpy as np

words = ["Python", "Data", "AI", "Machine", "Learning"]
lengths = np.array([len(w) for w in words])

print("단어 길이 배열:", lengths)
print("평균 길이:", np.mean(lengths))
print("가장 긴 단어 길이:", np.max(lengths))

단어 길이 배열: [6 4 2 7 8]
평균 길이: 5.4
가장 긴 단어 길이: 8


## 1️⃣ 실습 ① — 배열 생성 및 인덱싱

> 배열은 “순서가 있는 데이터 집합”입니다.
> 
> 
> 특정 위치의 값을 읽거나 수정할 수 있습니다.
>

In [ ]:
# 1차원
arr = np.array([10,20,30,40,50])
print(f"1차원 배열 : {arr} ")

#2차원
arr2 = np.array([[1,2,3], [4,5,6]])
print(f"2차원 배열 : {arr2}")


1차원 배열 : [10 20 30 40 50] 
2차원 배열 : [[1 2 3]
 [4 5 6]]


In [17]:
# 인덱싱
print(f"첫번째 요소 : {arr[0]}")
print(f"마지막요소 : {arr[-1]}")

# 수정
arr[2] = 99
print("수정후 배열", arr)

첫번째 요소 : 10
마지막요소 : 50
수정후 배열 [10 20 99 40 50]


## 2️⃣ 실습 ② — 슬라이싱(Slicing)

> 여러 개의 원소를 한꺼번에 선택하는 방법입니다.
> 
> 
> `[시작:끝:간격]` 형태로 작성합니다.
>

In [18]:
arr = np.array([5, 10, 15, 20, 25, 30])

print("처음 3개:", arr[:3])
print("중간 3개:", arr[2:5])
print("2개 간격으로:", arr[::2])
print("뒤에서부터:", arr[::-1])


처음 3개: [ 5 10 15]
중간 3개: [15 20 25]
2개 간격으로: [ 5 15 25]
뒤에서부터: [30 25 20 15 10  5]


✅ 데이터 분석 시 범위 추출에 자주 사용됨

---

## 3️⃣ 실습 ③ — 기본 통계 함수

> NumPy는 통계 계산에 최적화된 내장 함수를 제공합니다.
> 
> 
> (평균, 합계, 최솟값, 최댓값 등)
>

In [19]:
arr = np.array([10, 20, 30, 40, 50])

print("합계:", np.sum(arr))
print("평균:", np.mean(arr))
print("최댓값:", np.max(arr))
print("최솟값:", np.min(arr))
print("표준편차:", np.std(arr))


합계: 150
평균: 30.0
최댓값: 50
최솟값: 10
표준편차: 14.142135623730951


In [ ]:
# 랜덤
np.random.randint(1,46, size=6)

array([10,  9,  9,  7,  7, 28], dtype=int32)

## 4️⃣ 🧩 미니 프로젝트 — “단어 길이 통계 분석기” 📏

> 텍스트 데이터를 수치형 배열로 변환하여 분석하는 실습입니다.
> 
> 
> 넘파이의 수치 연산 능력을 텍스트 데이터 분석에 접목합니다.
>

In [21]:
import numpy as np

# 텍스트 데이터
words = ["Python", "AI", "Data", "Analysis", "Deep", "Learning"]

# 단어 길이 배열화
lengths = np.array([len(w) for w in words])
print("단어 길이 배열:", lengths)

# 통계 계산
print("평균 길이:", np.mean(lengths))
print("최댓값:", np.max(lengths))
print("분산:", np.var(lengths))

# 가장 긴 단어 찾기
max_len = np.max(lengths)
longest_word = [w for w in words if len(w) == max_len]
print("가장 긴 단어:", longest_word)

단어 길이 배열: [6 2 4 8 4 8]
평균 길이: 5.333333333333333
최댓값: 8
분산: 4.888888888888889
가장 긴 단어: ['Analysis', 'Learning']
